apiVersion: v1
kind: Service
metadata:
  name: web-app2
  namespace: devops
spec:
  selector:
    app: web-app2
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: app2
    protocol: TCP
    port: 80
    targetPort: 80