apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-app3
  namespace: devops
spec:
  selector:
    matchLabels:
      app: web-app3
  serviceName: "app3"
  replicas: 3
  template:
    metadata:
      labels:
        app: web-app3
    spec:
      containers:
      - name: app3
        image: devopsorient.azurecr.io/webpage8003:latest
        ports:
        - containerPort: 8003
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
        env:
          - name: MESSAGE
            value: 'App 3 !'
          - name: PORT
            value: '8003'