apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app4
  labels:
    app: web-app4
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app4
  template:
    metadata:
      labels:
        app: web-app4
    spec:
      containers:
      - name: app4
        image: devopsorient.azurecr.io/webpage8004:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
        env:
          - name: MESSAGE
            value: 'App 4 !'
          - name: PORT
            value: '80'